### ISSUE TITLE
Point be.camp domain to Github pages

### ISSUE THREAD

**Issue by AgentO3** [becamp/becamp.github.io#21]
DNS for be.camp will need to be updated to point it to github page. We should probably use the A record method. 

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

and point to the domain to the following IP address

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

I'm potentially open to using www.be.camp subdomain, but we'll need to make sure be.camp redirects correctly to www.be.camp

**Comment by andrew-boyd** [comment]
![Screenshot 2024-09-12 at 5 24 26 PM](https://github.com/user-attachments/assets/864597c6-91dc-4853-a386-7717e67d06e7)

Records added, and I moved over the google authentication txt record just in case.
